# Generated by Django 4.0.5 on 2022-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('phone_number', models.IntegerField(unique=True, verbose_name='전화 번호')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='가입 날짜')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
    ]
