# Generated by Django 4.0.5 on 2022-07-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_name_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, verbose_name='비밀번호'),
        ),
    ]
