# Generated by Django 4.0.5 on 2022-07-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='질문 날짜'),
        ),
    ]
