# Generated by Django 4.0.5 on 2022-07-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('기타문의', '기타문의'), ('가격문의', '가격문의'), ('시술문의', '시술문의')], default='기타문의', max_length=10),
            preserve_default=False,
        ),
    ]
