# Generated by Django 4.0.5 on 2022-07-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.CharField(choices=[('입술 반영구', '입술 반영구'), ('눈썹 반영구', '눈썹 반영구'), ('아이라인', '아이라인'), ('헤어 라인', '헤어 라인')], default='아이라인', max_length=10, verbose_name='예약 서비스'),
            preserve_default=False,
        ),
    ]
